[metadata]
name = neutropenia
version = 7.0.0
author = BCH Health NLP Lab
author_email = eli.goldner@childrens.harvard.edu
description = Neutropenia clinical genomics extractor for DeepPhe
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/apache/ctakes
project_urls =
    Bug Tracker = https://github.com/apache/ctakes/issues
classifiers =
    Programming Language :: Python :: 3.10
    Operating System :: OS Independent
    License :: OSI Approved :: Apache Software License

[options]
package_dir=
    = src
packages = find:
python_requires = >=3.10
install_requires =
    ctakes-pbj~=7.0.0

[options.packages.find]
where = src
